
server:
  port: 8002
spring:
  application:
    name: reservation-service

eureka:
  instance:
    ip-address: 43.201.81.76
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
