
server:
  port: 8002
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ai-gong
  application:
    name: reservation-service

eureka:
  instance:
    ip-address: 127.0.0.1
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
