spring:
    profiles:
        group:
            "local" : "local, jwt, oauth"
        active: local

server:
  port: 8083
  
eureka:
    instance:
        ip-address: 43.201.81.76
        preferIpAddress: true
        lease-renewal-interval-in-seconds: 30
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

---
spring:
    config:
        activate:
            on-profile: "local"
    data:
        mongodb:
            host: localhost
            port: 27017
            database: ai-gong
    application:
        name: auth-service
    main:
        allow-bean-definition-overriding: true